language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
- sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
- sudo apt-get update -qq

install:
- sudo apt-get -y install qt59base qt59x11extras qt59tools
- source /opt/qt*/bin/qt*-env.sh

jobs:
  include:
    - stage: build
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make
    - stage: test
      script:
        - make test
